name: Aggiornamento Giornaliero EPG

on:
  schedule:
    # Esegue ogni giorno alle 03:00 UTC (le 04:00 o 05:00 in Italia a seconda dell'ora legale)
    - cron: '0 6 * * *'
  workflow_dispatch: # Permette di avviarlo manualmente dalla scheda Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installa libreria requests
        run: pip install requests

      - name: Esegui lo script di filtraggio
        run: python filter_epg.py

      - name: Carica i cambiamenti sul repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add 02.xmltv
          git commit -m "Aggiornamento automatico EPG (La7 Cinema e Radio Italia)" || echo "Nessuna modifica"
          git push
